/**
 * Generates SQL INSERT statements to seed all built-in movements into
 * the custom_movements table. Run with: node scripts/seed_movements.mjs
 */

import {
  BODYWEIGHT_EXERCISE_NAMES,
  ISOMETRIC_EXERCISE_NAMES,
  STRENGTH_MOVEMENTS,
  CARDIO_MOVEMENTS,
  ASSISTED_MACHINE_NAMES,
  CARRY_EXERCISES,
  BAND_ASSIST_ELIGIBLE,
  KNEE_ASSIST_ELIGIBLE,
} from '../src/lib/movements.js'

// Mirror of the dumbbell keyword heuristic in formulas.js
const DUMBBELL_KEYWORDS = [
  'dumbbell', ' db ', 'dumbell',
  'kettlebell', 'goblet squat', 'concentration curl', 'renegade row',
  'single arm', 'one arm',
]
function isDumbbell(name) {
  const lower = name.toLowerCase()
  return DUMBBELL_KEYWORDS.some(kw => lower.includes(kw))
}

// Mirror of cardio duration set from movements.js
const CARDIO_DURATION_SET = new Set([
  'Agility Ladder Drills', 'Arc Trainer', 'Battle Ropes', 'Bear Crawl',
  'Box Step Overs', 'Carioca', 'Crab Walk', "Jacob's Ladder", 'Jump Rope',
  'Lateral Shuffles', 'Line Drills', 'Low Crawl', 'Shadow Boxing',
  'Shuttle Run', 'Slideboard', 'Speed Bag', 'StairMill', 'VersaClimber',
])

// ── Escape single quotes for SQL ──────────────────────────────────────────────
function esc(s) { return s.replace(/'/g, "''") }

// ── Classify a strength movement ──────────────────────────────────────────────
function classifyStrength(name) {
  if (ISOMETRIC_EXERCISE_NAMES.has(name)) {
    return { strength_type: 'isometric', equipment: null, band_assist: false, knee_assist: false }
  }
  if (CARRY_EXERCISES.has(name)) {
    return { strength_type: 'rep-based', equipment: 'carry', band_assist: false, knee_assist: false }
  }
  if (ASSISTED_MACHINE_NAMES.has(name)) {
    return { strength_type: 'rep-based', equipment: 'assisted', band_assist: false, knee_assist: false }
  }
  if (BODYWEIGHT_EXERCISE_NAMES.has(name)) {
    return {
      strength_type: 'rep-based',
      equipment: 'bodyweight',
      band_assist: BAND_ASSIST_ELIGIBLE.has(name),
      knee_assist: KNEE_ASSIST_ELIGIBLE.has(name),
    }
  }
  if (isDumbbell(name)) {
    return { strength_type: 'rep-based', equipment: 'dumbbell', band_assist: false, knee_assist: false }
  }
  // Default: barbell / plate-loaded / cable machine
  return { strength_type: 'rep-based', equipment: 'barbell', band_assist: false, knee_assist: false }
}

// ── Build rows ────────────────────────────────────────────────────────────────

const rows = []

// Strength
for (const name of STRENGTH_MOVEMENTS) {
  const { strength_type, equipment, band_assist, knee_assist } = classifyStrength(name)
  rows.push(
    `('${esc(name)}', 'strength', '${strength_type}', ${equipment ? `'${equipment}'` : 'null'}, ${band_assist}, ${knee_assist}, null)`
  )
}

// Cardio
for (const name of CARDIO_MOVEMENTS) {
  const cardio_mode = CARDIO_DURATION_SET.has(name) ? 'duration' : 'pace'
  rows.push(
    `('${esc(name)}', 'cardio', null, null, false, false, '${cardio_mode}')`
  )
}

// ── Output SQL ────────────────────────────────────────────────────────────────

console.log(`-- Seed: insert all built-in movements into custom_movements`)
console.log(`-- Generated by scripts/seed_movements.mjs`)
console.log(`-- ON CONFLICT DO NOTHING so safe to re-run`)
console.log(``)
console.log(`INSERT INTO custom_movements`)
console.log(`  (name, category, strength_type, equipment, band_assist, knee_assist, cardio_mode)`)
console.log(`VALUES`)
console.log(rows.join(',\n'))
console.log(`ON CONFLICT (name) DO NOTHING;`)
console.log(``)
console.log(`-- Total rows: ${rows.length}`)
